import fs from 'node:fs/promises';
import {Workbook,SpreadsheetFile} from '@oai/artifact-tool';
const [bundlePath='outputs/excel_bundle.json',out='outputs/Sabah_Rail_Audit_v0.2.0.xlsx']=process.argv.slice(2);
const b=JSON.parse(await fs.readFile(bundlePath,'utf8')),d=b.data,r=b.selected,wb=Workbook.create();
const names=['Summary','Controls','Passenger Forecasts','Passenger Calculation','Freight Calculation','Freight OD','Passenger Sample OD','Survey QA','Traffic Counts','Station Catchments','Operations','Road Safety Economics','Scenarios','Sensitivity','Source Register','Assumptions','Unresolved','Run Register','Calculation Trail','QA'];
for(const name of names)wb.worksheets.add(name);
function col(n){let s='';for(n++;n;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s}
function sheet(name,title,heads,rows){let s=wb.worksheets.getItem(name),end=col(heads.length-1);s.showGridLines=false;s.tabColor='#245C91';s.getRange(`A1:${end}1`).merge();s.getRange('A1').values=[[title]];s.getRange(`A1:${end}1`).format={fill:'#14253B',font:{color:'#FFFFFF',bold:true,size:15},rowHeight:32};s.getRange(`A3:${end}3`).values=[heads];s.getRange(`A3:${end}3`).format={fill:'#245C91',font:{color:'#FFFFFF',bold:true},rowHeight:30,wrapText:true};if(rows.length)s.getRange(`A4:${end}${rows.length+3}`).values=rows.map(row=>row.map(v=>v===undefined?null:typeof v==='object'&&v!==null?JSON.stringify(v):v));s.getRange(`A4:${end}${Math.max(4,rows.length+3)}`).format={font:{name:'Arial',size:10},rowHeight:28,wrapText:true,numberFormat:'#,##0.00;[Red](#,##0.00);–'};s.getRange(`A:${end}`).format.columnWidth=22;s.getRange('A:A').format.columnWidth=30;s.freezePanes.freezeRows(3);return s}
const ctrl=sheet('Controls','SELECTED PYTHON RUN · snapshot, not approved baseline',['Parameter','Value','Unit / status'],[['Year',r.scenario.year,'year'],['Case',r.scenario.case,'Draft'],['Option',r.scenario.option,'Alternative'],['Daily source trips',r.passenger.daily_source_trips,'source trips/day'],['Passenger days',r.effective_assumptions.passenger_days,'days/year · source'],['Freight days',r.effective_assumptions.freight_days,'days/year · draft'],['Headway',r.operations.headway_min,'minutes · draft'],['Service hours',r.operations.service_hours,'hours/day · draft'],['Source PPHPD',r.operations.source_pphpd,'passengers/hour/direction · draft'],['Train capacity',null,'Unresolved passengers/train'],['Data version',r.data_version,'SHA256'],['Model / Git',r.model_version+' / '+r.git_version,'release'],['Run ID',r.run_id,'immutable snapshot']]);ctrl.getRange('B4:B16').format.font.color='#008000';ctrl.getRange('B:B').format.columnWidth=45;
const summ=sheet('Summary','SABAH RAIL · V0.2 DRAFT AUDIT',['Measure','Result','Interpretation'],[['Passenger source trips / day',null,'Unique journey interpretation unresolved'],['Passenger source trips / year',null,'365-day source convention'],['Freight cargo / year',null,'v4.7 / selected package · tonnes'],['Freight units / year',null,'TEU including empty equipment'],['Headway',null,'minutes; no calibrated demand elasticity'],['Net road VKT avoided','UNRESOLVED','Diversion / occupancy / haul / access data needed'],['Accidents avoided','UNRESOLVED','Comparable road exposure needed'],['Station OD and line loading','UNRESOLVED','Do not use catchment IN/OUT as boardings'],['Project NPV / BCR','UNRESOLVED','Approved appraisal inputs/cost streams needed'],['Release status','DRAFT_PARTIAL','Working model; no approved forecast baseline'],['Cloud status','NOT DEPLOYED','GCP authentication and persistent DB pending'],['Evidence','20 source files','Originals preserved; see register'],['Automated tests','29 PASS','Does not validate missing project inputs']]);summ.getRange('C:C').format.columnWidth=68;summ.getRange('B4').formulas=[["=Controls!B7"]];summ.getRange('B5').formulas=[["='Passenger Calculation'!B5"]];summ.getRange('B6').formulas=[["=SUM('Freight Calculation'!P4:P40)"]];summ.getRange('B7').formulas=[["=SUM('Freight Calculation'!O4:O40)"]];summ.getRange('B8').formulas=[["=Controls!B10"]];
const pf=[];for(const [cas,opts]of Object.entries(d.passenger_forecasts.summary_draft))for(const [opt,pts]of Object.entries(opts))for(const [year,val]of Object.entries(pts))pf.push([cas,+opt,+year,val,'source trips/day','P_SUMMARY','Draft']);sheet('Passenger Forecasts','SOURCE SCHEDULES · Low / Base / High preserved',['Case','Option','Year','Daily','Unit','Source','Status'],pf);
const pc=sheet('Passenger Calculation','PASSENGER ANNUALISATION · Excel mirror of Python',['Calculation','Excel result','Python reference','Residual','Source / equation'],[['Daily source trips',null,r.passenger.daily_source_trips,null,'Selected source schedule, explicit interpolation if needed'],['Annual source trips',null,r.passenger.annual_source_trips,null,'Daily × passenger operating days']]);pc.getRange('B4').formulas=[['=Controls!B7']];pc.getRange('B5').formulas=[['=B4*Controls!B8']];pc.getRange('D4:D5').formulas=[['=B4-C4'],['=B5-C5']];pc.getRange('E:E').format.columnWidth=60;
const fm=r.freight.markets.map(v=>{const raw=d.freight_markets.find(x=>x.id===v.id);return[v.id,v.origin,v.destination,v.market_volume,v.market_unit,...v.factors,v.ramp,raw.laden_share,raw.cargo_per_laden_teu,raw.container?1:0,null,null,v.tonnes_year,v.teu_year,null,v.source_cell,v.status]});
const fc=sheet('Freight Calculation','FREIGHT MARKET CHAIN · input factors → captured cargo',['Market','Origin','Destination','Future market','Unit','Development','Rail suitable','Commodity suitable','Terminal','Capture','Ramp','Laden share','t/laden TEU','Container flag','Excel TEU/year','Excel tonnes/year','Python tonnes/year','Python TEU/year','Tonnes residual','Source cells','Status'],fm);
for(let i=4;i<fm.length+4;i++){fc.getRange(`O${i}`).formulas=[[`=IF(N${i}=1,D${i}*F${i}*G${i}*H${i}*I${i}*J${i}*K${i},0)`]];fc.getRange(`P${i}`).formulas=[[`=IF(N${i}=1,O${i}*L${i}*M${i},D${i}*F${i}*G${i}*H${i}*I${i}*J${i}*K${i})`]];fc.getRange(`S${i}`).formulas=[[`=P${i}-Q${i}`]]}fc.getRange('T:T').format.columnWidth=42;
sheet('Freight OD','DIRECTIONAL FREIGHT OD · selected draft market allocation',['Origin','Destination','Tonnes/year','TEU/year','Status'],r.freight.od.map(x=>[x.origin,x.destination,x.tonnes_year,x.teu_year,'Draft; N4/N5 disaggregation unresolved']));
sheet('Passenger Sample OD','PASSENGER OD · UNWEIGHTED SURVEY RESPONDENTS, not forecasts',['Reported origin','Reported destination','Respondents','Source','Status'],d.passenger_survey.sample_od.map(x=>[x.origin,x.destination,x.respondents,'P_SURVEY','Unresolved zone mapping / expansion']));
sheet('Survey QA','SURVEY RECONCILIATION',['Measure','Value','Status'],[['Passenger raw rows',d.passenger_survey.raw_rows,'Unresolved selected sample'],['Reported TN3 sample',d.passenger_survey.reporting_sample_tn3,'Alternative report'],['Exact duplicate rows',d.passenger_survey.exact_duplicate_rows,'Count only; no silent removals'],['Missing OD',d.passenger_survey.missing_od,'Do not invent endpoints'],['Freight respondents',d.freight_survey.respondents,'Small sample; no market expansion'],...Object.entries(d.passenger_survey.modes).map(([k,v])=>[k,v,'Source responses'])]);
sheet('Traffic Counts','TRAFFIC ANALYSIS · separate directional PCU/hour observations',['Site','Direction','Period','Duration h','PCU/hour','Capacity','Source cell','Status'],d.screenline_counts.map(x=>[x.station,x.direction,x.period,x.duration_hours,x.value,x.capacity,x.source_cell,x.status]));
sheet('Station Catchments','STATION CATCHMENT TRIP ENDS · NOT BOARDINGS',['Station','Daily IN','Daily OUT','AM IN','AM OUT','Source row','Status'],d.station_catchment_outputs.map(x=>[x.name,x.daily_in,x.daily_out,x.am_in,x.am_out,x.source_row,x.status]));
const ops=sheet('Operations','RAIL SERVICE · capacity assumptions remain explicit',['Measure','Value','Unit / status'],[['Trains/hour/direction',null,'train paths/hour'],['Departures/day, both directions',null,'train departures/day'],['Source PPHPD',r.operations.source_pphpd,'Draft source peak; not assigned load'],['Capacity PPHPD','UNRESOLVED','Supply usable train capacity'],['Freight trains/day','UNRESOLVED','Supply effective TEU/t per train, path limits']]);ops.getRange('B4').formulas=[['=60/Controls!B10']];ops.getRange('B5').formulas=[['=B4*Controls!B11*2']];
sheet('Road Safety Economics','IMPACTS · unresolved outputs withheld',['Measure','Value','Unit / status'],[['Historical accidents',d.accidents.total,'accidents 2019–2025, not persons'],['Historical annual accidents',d.accidents.total/7,'accidents/year; corridor scope must match VKT'],['Road vehicle trips removed',null,'Unresolved diversion / occupancy'],['Net VKT avoided',null,'Unresolved feeder/access VKT'],['Accidents avoided',null,'Unresolved comparable exposure denominator'],['Door-to-door time savings',null,'Unresolved mode travel times'],['Annual economic benefits',null,'Unresolved approved unit values / demand split'],['Revenue / financial surplus',null,'Unresolved fares / tariffs / costs'],['NPV / BCR',null,'No invented capital/operating cost stream']]);
sheet('Scenarios','SAVED PYTHON RUNS · source variant separate from scenario',['Case','Year','Option','Freight variant','Package','Passenger trips/day','Freight t/year','Freight TEU/year','Validation','Run ID'],b.runs.map(x=>[x.scenario.case,x.scenario.year,x.scenario.option,x.scenario.freight_variant,x.scenario.freight_package,x.passenger.daily_source_trips,x.freight.tonnes_year,x.freight.teu_year,x.validation_status,x.run_id]));
sheet('Sensitivity','HEADWAY SENSITIVITY · no calibrated demand response assumed',['Headway min','Trips/day','Trains/h/direction','Capacity','Status','Run ID'],b.sensitivity.map(x=>[x.operations.headway_min,x.passenger.daily_source_trips,x.operations.trains_per_hour_direction,x.operations.capacity_pphpd,'Demand unchanged without explicit elasticity',x.run_id]));
sheet('Source Register','MASTER SOURCE REGISTER · hashes and status preserved',['Source ID','File','SHA256','Bytes','Classification','Source date','Approval evidence','Original location'],d.sources.map(x=>[x.id,x.file,x.sha256,x.bytes,x.classification,x.source_date,x.approval_evidence,x.path]));
sheet('Assumptions','EFFECTIVE RUN ASSUMPTIONS',['Name','Value','Status','Source / treatment'],Object.entries(r.effective_assumptions).map(([k,v])=>[k,v,'Draft','Source convention or working configuration; not approval']));
sheet('Unresolved','BASELINE CONFLICTS AND DATA GAPS',['ID','Domain','Issue','Action','Status'],d.unresolved.map(x=>[x.id,x.domain,x.issue,x.action,x.status]));for(const c of ['C:C','D:D'])wb.worksheets.getItem('Unresolved').getRange(c).format.columnWidth=70;
sheet('Run Register','IMMUTABLE RUN REGISTER',['Run ID','Timestamp UTC','Model','Git','Data SHA256','Scenario','Forecast year','Validation'],[...b.runs,...b.sensitivity].map(x=>[x.run_id,x.timestamp,x.model_version,x.git_version,x.data_version,JSON.stringify(x.scenario),x.scenario.year,x.validation_status]));
sheet('Calculation Trail','PYTHON CALCULATION TRACE',['Output','Value','Unit','Equation','Source IDs','Source cells','Status','Dependencies'],r.trace.map(x=>[x.output,x.value,x.unit,x.equation,x.sources,x.source_cell,x.status,x.dependencies]));
const qa=sheet('QA','RELEASE CHECKS · formula reconciliation + missing-data flags',['Check','Status / residual','Interpretation'],[['Passenger daily residual',null,'Absolute residual ≤ 0.00001'],['Passenger annual residual',null,'Absolute residual ≤ 0.00001'],['Freight cargo residual sum',null,'Absolute residual ≤ 0.00001'],['Freight TEU residual',null,'Absolute residual ≤ 0.00001'],...r.checks.map(x=>[x.check,x.status,'Python run check']),['Unit / integration / regression suite','29 PASS','Cloud Work execution; see QA report'],['GCP deployed','NOT RUN','Authentication / database pending'],['Gemini independent review','NOT RUN','No authenticated Gemini environment'],['Network calibration','UNRESOLVED','No calibrated assignment or station OD']]);qa.getRange('B4:B7').formulas=[["=ABS('Passenger Calculation'!D4)"],["=ABS('Passenger Calculation'!D5)"],[`=ABS(SUM('Freight Calculation'!S4:S${fm.length+3}))`],[`=ABS(SUM('Freight Calculation'!O4:O${fm.length+3})-SUM('Freight Calculation'!R4:R${fm.length+3}))`]];qa.getRange('C:C').format.columnWidth=64;
// Reserve a separate summary area for range-linked scenario charts.
summ.getRange('A20:D28').values=[['Year','Low','Base','High'],...[2033,2038,2043,2045,2048,2053,2058,2063].map(y=>[y,...['Low','Base','High'].map(c=>b.runs.find(x=>x.scenario.case===c&&x.scenario.year===y&&x.scenario.freight_variant==='v47_draft').passenger.daily_source_trips)])];summ.getRange('A20:D20').format={fill:'#245C91',font:{color:'#FFFFFF',bold:true}};summ.getRange('A20:A28').setNumberFormat('0');const chart=summ.charts.add('line',summ.getRange('A20:D28'));chart.title='Option 3 · draft passenger source trips/day';chart.setPosition('A31','D46');chart.yAxis={numberFormatCode:'#,##0',numberFormatSourceLinked:false};
wb.recalculate();console.log((await wb.inspect({kind:'region',sheetId:'QA',range:'A3:C8',maxChars:2000})).ndjson);const blob=await SpreadsheetFile.exportXlsx(wb);await blob.save(out);const png=await wb.render({sheetName:'Summary',range:'A1:C17',scale:1.2,format:'png'});await fs.writeFile(out.replace('.xlsx','_preview.png'),new Uint8Array(await png.arrayBuffer()));console.log('Exported',out);
