"""Public synthetic execution fixture; no Sabah Rail numerical evidence."""
import hashlib,json

def synthetic_data():
 years=[2024,2033,2038,2043,2048,2053,2058,2063]
 forecasts={case:{str(opt):{str(y):(80+20*opt)*(1+0.01*(y-2024))*mult for y in years}for opt in range(1,8)}for case,mult in [('Low',0.8),('Base',1),('High',1.2)]}
 peaks={c:{o:{y:v*0.1 for y,v in pts.items()}for o,pts in opts.items()}for c,opts in forecasts.items()}
 market={'id':'SYN01','origin':'A','destination':'B','service':'SV1','direction':'A','package':'S1','commodity':'Synthetic cargo','container':True,'market_volume':100,'unit':'TEU','laden_share':1,'cargo_per_laden_teu':5,'source':'SYNTHETIC','source_cell':'fixture, not project cell','included':True,'port_allocation':0.1,'growth':[0,0,0],'base_year':2024,'development':[1,1,1],'rail_suitability':[1,1,1],'commodity_suitability':[1,1,1],'terminal':[1,1,1],'capture':[0.1,0.2,0.3],'ramp':True}
 return {'schema_version':'0.3','governance_status':'SYNTHETIC TEST ONLY — NOT PROJECT FORECAST','passenger_forecasts':{'summary_draft':forecasts,'tn3_high_only':{'High':{'3':forecasts['High']['3']}}},'passenger_peaks':peaks,'passenger_controls':{},'station_catchment_outputs':[],'freight_controls':{'port_actual':1000,'port_year':2024,'growth':[0,0,0],'capacity':2000,'land_share':1,'status':'Synthetic test'},'freight_markets':[market],'freight_headline':{c:{'2033':10,'2043':20,'2053':30,'2063':40}for c in forecasts},'freight_regression':[],'historical_rail_freight':[],'screenline_counts':[],'passenger_survey':{'source':'SYNTHETIC','raw_rows':0,'reporting_sample_tn3':0,'sample_od':[],'modes':{},'missing_od':0,'exact_duplicate_rows':0},'freight_survey':{'respondents':0,'od_evidence':[]},'accidents':{'total':7,'year_start':2019,'year_end':2025,'fatal_accidents':1,'serious_injury_accidents':2,'minor_injury_accidents':3,'pdo_accidents':1,'status':'Synthetic fixture, not accident evidence'},'geography':{'features':0,'status':'Synthetic test'},'sources':[{'id':'SYNTHETIC','file':'fixture.py','classification':'Workaround','sha256':'not-project-evidence','source_date':None,'approval_evidence':None}],'unresolved':[{'id':'SYNTHETIC_ONLY','domain':'Execution test','issue':'Synthetic inputs','action':'Private approved or explicitly Draft project inputs required for project runs','status':'Unresolved'}]}
